// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcTu-5Snv8wgUbrFGCIi0Jv4skF7rxw2I',
    appId: '1:1057411894938:android:309c2410e30cdb1bd65923',
    messagingSenderId: '1057411894938',
    projectId: 'examprogmob',
    storageBucket: 'examprogmob.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfcRcaYBvGH4u-dXx1MbdnhfNNLNDjb2U',
    appId: '1:1057411894938:ios:e7539af6282841efd65923',
    messagingSenderId: '1057411894938',
    projectId: 'examprogmob',
    storageBucket: 'examprogmob.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs3ZU5vSJ8GJKASvDotq7jOCXBA5aMUPs',
    appId: '1:1057411894938:web:4e1c7adc44cb0f18d65923',
    messagingSenderId: '1057411894938',
    projectId: 'examprogmob',
    authDomain: 'examprogmob.firebaseapp.com',
    storageBucket: 'examprogmob.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfcRcaYBvGH4u-dXx1MbdnhfNNLNDjb2U',
    appId: '1:1057411894938:ios:e7539af6282841efd65923',
    messagingSenderId: '1057411894938',
    projectId: 'examprogmob',
    storageBucket: 'examprogmob.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs3ZU5vSJ8GJKASvDotq7jOCXBA5aMUPs',
    appId: '1:1057411894938:web:3ec606835d632331d65923',
    messagingSenderId: '1057411894938',
    projectId: 'examprogmob',
    authDomain: 'examprogmob.firebaseapp.com',
    storageBucket: 'examprogmob.firebasestorage.app',
  );

}